version: '3.8'
services:
  vue-frontend:
    container_name: vue-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./front:/usr/src
      - /usr/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  node-backend:
    container_name: node-backend
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    volumes:
      - ./back:/usr/src
      - /usr/src/node_modules
    environment:
      - MONGO_USERNAME=eloi
      - MONGO_PASSWORD=unsafe_password
      - MONGO_HOSTNAME=mongo-db
      - MONGO_PORT=27017
      - MONGO_DB=stationf-test
    depends_on:
      - db
    networks:
      - network

  db:
#    Command Line Connect:
#     docker exec -ti db bash
#     mongo "mongodb://eloi:unsafe_password@db:27017/stationf-test?authSource=admin"
    container_name: db
    image: mongo:4.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eloi
      - MONGO_INITDB_ROOT_PASSWORD=unsafe_password
      - MONGO_INITDB_DATABASE=stationf-test
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  dbdata:
  node_modules:


